### ISSUE TITLE
cmus bar problem (ncurses) / emoji & unicode

### ISSUE THREAD

**Issue by HalanoSiblee** [summaryInfo/nsst#3]
using [cmus](https://github.com/cmus/cmus) as my default music player
I've face two problems
1. many ncurses tui not just cmus had weird rendering
2. emoji and some unicode are broken

Here an preview of cmus bar problem compares to other terms
![nsstcprobs](https://github.com/user-attachments/assets/374a1746-be4e-443e-b5f2-f164712cf08b)
here my cmus dots `~/.config/cmus` > [autosave.tar.gz](https://github.com/user-attachments/files/17598006/autosave.tar.gz) 
emoji problem comparison :
![01-11-30-1730460634](https://github.com/user-attachments/assets/629889da-1f34-4357-a236-4b2d8ea5b9df)

**Comment by summaryInfo** [comment]
Can you please provide nsst config and logs with `--trace-controls --trace-characters` for the rendering issue and
with `--trace-fonts` for the Unicode issue?

The status bar was rendering correctly for me in cmus, is it possible that foreground and background
colors are the same? (To confirm or disprove that I need the logs though)

![2024-11-01-150135_624x496_scrot](https://github.com/user-attachments/assets/7f5beb98-c86a-4f41-9691-a585bb820616)

As for the Unicode issue, I suspect that the terminal loads SVG font, which it cannot render.
For me emoji from SVG fonts don't render in all of the above terminals. I've pushed a workaround
for that issue, but it will cause emoji to render in grayscale. To have proper emoji you can
explicitly specify the font that contains emoji after your main font in a format that freetype
can render to a bitmap. E.g. `Noto Color Emoji` is known to work. Please let me know it that
works for you.

**Comment by HalanoSiblee** [comment]
`term-name=xterm-256color` fixed the problem
I see you still use the old xterm logic
It's better to isolate nsst
and set 256 ture color by default
```patch
--- config.c	2024-10-30 22:32:08.846908510 +0000
+++ patch.c	2024-11-01 15:34:45.408189730 +0000
@@ -336,7 +336,7 @@
     X(time, sync_time, "sync-timeout", "Synchronous update timeout", SEC/2, 0, 10*SEC),
     X(int16, tab_width, "tab-width", "Initial width of tab character", 8, 1, 1000),
     X(string, term_mod, "term-mod", "Meaning of 'T' modifier", "SC"),
-    X1(string, terminfo, 'D', "term-name", "TERM value", "xterm"),
+    X1(string, terminfo, 'D', "term-name", "TERM value", "xterm-256color"),
     X2(string, title, 'T', 't', "title", "Initial window title", "Not So Simple Terminal"),
     X(dim, border.top, "top-border", "Top border size", 0, 0, 200),
     G(boolean, trace_characters, "trace-characters", "Trace interpreted characters", false),
```
What about the Emoji rendering ?

**Comment by HalanoSiblee** [comment]
the svg emoji render well on suckless terminal & alacrity It's _`Twemoji.ttf`_

**Comment by summaryInfo** [comment]
Thanks for the patch! But I already pushed the new default to master.
Nsst is very compatible with xterm in terms of control sequences support, so it will work fine.
Nsst-specific terminfo is shipped with the terminal, although for 2 reasons it is not the default one:

1. Some applications hardcode terminal names and don't work well with custom terminfo.
2. nsst terminfo installs with the terminal so it is absent on remote systems which breaks ssh.

As for emoji rendering you may try the workaround in master, which avoids SVG glyphs,
but it falls back to the monochrome emojis. Right now you can specify non-SVG font explicitly
after your main font, like:
```
font=BlexMono Nerd Font Mono-11,Noto Color Emoji
```

Later I'll look into a way to avoid or render SVG-fonts automatically, but afaik other terminals don't do that.
It seems interesting, that it works in st&alacritty, since for me it doesn't and there's no special handling for that.

**Comment by summaryInfo** [comment]
BTW there is ![a version  of Twemoji](https://github.com/JoeBlakeB/ttf-twemoji-aur) that works for nsst

**Comment by HalanoSiblee** [comment]
Thanks for this truetype version of Twemoji it work perfect with nsst atm.
🎃 Happy Halloween 🎃
![image](https://media.tenor.com/l3YqYl4BP-IAAAAj/sappy-seals.gif)
